# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
        ('willys_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpageheroitem',
            name='heroitem_ptr',
        ),
        migrations.RemoveField(
            model_name='blogpageheroitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='eventpageheroitem',
            name='heroitem_ptr',
        ),
        migrations.RemoveField(
            model_name='eventpageheroitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='time_to',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.DeleteModel(
            name='BlogPageHeroItem',
        ),
        migrations.DeleteModel(
            name='EventPageHeroItem',
        ),
    ]
