# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 10:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willys_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagehero',
            name='color',
            field=models.CharField(blank=True, help_text='Background Color Hex #ffffff', max_length=7, null=True, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='homepagehero',
            name='position',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default=('R', 'Right'), max_length=1),
        ),
    ]
