# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('willys_website', '0002_auto_20170129_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
    ]
