# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willys_website', '0002_auto_20161230_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagehero',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='homepagehero',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
