# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willys_website', '0002_landingpage_landingpagehero_landingpagerelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='claim',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='subclaim',
            field=models.CharField(max_length=255),
        ),
    ]
