# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('willys_website', '0003_homepage_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='media',
            new_name='video',
        ),
    ]
