# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('willys_website', '0003_auto_20170126_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='subclaim',
        ),
    ]
