# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('willys_website', '0003_auto_20161220_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_video_id',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_video_poster_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_title',
        ),
    ]
