# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('willys_website', '0004_auto_20170126_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='landingpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='landingpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='heroitem',
            name='position',
        ),
        migrations.DeleteModel(
            name='LandingPageRelatedLink',
        ),
    ]
