# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willys_website', '0004_auto_20161220_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagehero',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='homepagehero',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepagehero',
            name='logo',
        ),
        migrations.AddField(
            model_name='homepagehero',
            name='color',
            field=models.CharField(help_text='Background Color Hex #ffffff', max_length=255, null=True),
        ),
    ]
