# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willys_website', '0005_auto_20170129_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpage',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='productpage',
            name='ibu',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpage',
            name='proof',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpage',
            name='style',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpage',
            name='subtitle',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productpage',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
