# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willys_website', '0005_standardpage_standardpageheroitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='location_name',
            field=models.CharField(default='notset', max_length=255),
        ),
    ]
