# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('willys_website', '0007_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='twitter_handle',
            new_name='twitter_url',
        ),
    ]
